# Generated by Django 6.1 on 2026-09-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('charger_id', models.BigAutoField(db_column='ChargerID', primary_key=True, serialize=False)),
                ('charger_number', models.IntegerField(db_column='ChargerNumber')),
                ('charger_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], db_column='ChargerType', max_length=30)),
                ('power_output', models.DecimalField(db_column='PowerOutput', decimal_places=2, max_digits=6)),
                ('price_per_kwh', models.DecimalField(db_column='PricePerKWh', decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], db_column='Status', max_length=20)),
            ],
            options={
                'db_table': 'CHARGERS',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.BigAutoField(db_column='StationID', primary_key=True, serialize=False)),
                ('station_name', models.CharField(db_column='StationName', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('city', models.CharField(db_column='City', max_length=50)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=7, max_digits=10, null=True)),
                ('opening_time', models.CharField(blank=True, db_column='OpeningTime', max_length=10, null=True)),
                ('closing_time', models.CharField(blank=True, db_column='ClosingTime', max_length=10, null=True)),
            ],
            options={
                'db_table': 'STATIONS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='FullName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('phone', models.CharField(db_column='Phone', max_length=15, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Owner', 'Owner'), ('Admin', 'Admin')], db_column='Role', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='DateCreated')),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(db_column='BookingID', primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(db_column='BookingDate')),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('end_time', models.DateTimeField(db_column='EndTime')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_column='Status', max_length=20)),
                ('charger', models.ForeignKey(db_column='ChargerID', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='charging.charger')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='charging.user')),
            ],
            options={
                'db_table': 'BOOKINGS',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('report_id', models.BigAutoField(db_column='ReportID', primary_key=True, serialize=False)),
                ('issue_type', models.CharField(db_column='IssueType', max_length=100)),
                ('description', models.CharField(db_column='Description', max_length=500)),
                ('status', models.CharField(db_column='Status', max_length=30)),
                ('report_date', models.DateTimeField(db_column='ReportDate')),
                ('booking', models.ForeignKey(db_column='BookingID', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='charging.booking')),
                ('charger', models.ForeignKey(db_column='ChargerID', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='charging.charger')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='charging.user')),
            ],
            options={
                'db_table': 'MAINTENANCE_REPORTS',
            },
        ),
        migrations.AddField(
            model_name='charger',
            name='station',
            field=models.ForeignKey(db_column='StationID', on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='charging.station'),
        ),
        migrations.AddField(
            model_name='station',
            name='owner',
            field=models.ForeignKey(db_column='OwnerID', on_delete=django.db.models.deletion.CASCADE, related_name='owned_stations', to='charging.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(db_column='ReviewID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=500, null=True)),
                ('review_date', models.DateTimeField(db_column='ReviewDate')),
                ('station', models.ForeignKey(db_column='StationID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='charging.station')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='charging.user')),
            ],
            options={
                'db_table': 'REVIEWS',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=200)),
                ('message', models.CharField(db_column='Message', max_length=500)),
                ('is_read', models.CharField(db_column='IsRead', default='N', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='charging.user')),
            ],
            options={
                'db_table': 'NOTIFICATIONS',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVerification',
            fields=[
                ('verification_id', models.BigAutoField(db_column='VerificationID', primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], db_column='Result', max_length=50)),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=500, null=True)),
                ('verification_date', models.DateTimeField(db_column='VerificationDate')),
                ('report', models.ForeignKey(db_column='ReportID', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='charging.maintenancereport')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_verifications', to='charging.user')),
            ],
            options={
                'db_table': 'MAINTENANCE_VERIFICATION',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus'), ('Other', 'Other')], max_length=30)),
                ('battery_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='charging.user')),
            ],
            options={
                'db_table': 'VEHICLES',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(db_column='VehicleID', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='charging.vehicle'),
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('session_id', models.BigAutoField(db_column='SessionID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_column='StartTime')),
                ('end_time', models.DateTimeField(db_column='EndTime')),
                ('units_consumed', models.DecimalField(db_column='UnitsConsumed', decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(db_column='TotalCost', decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(db_column='BookingID', on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='charging.booking')),
            ],
            options={
                'db_table': 'CHARGING_SESSIONS',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='CK_CHARGING_SESSIONS_TIME'), models.CheckConstraint(condition=models.Q(('units_consumed__gt', 0)), name='CK_CHARGING_SESSIONS_UNITS'), models.CheckConstraint(condition=models.Q(('total_cost__gte', 0)), name='CK_CHARGING_SESSIONS_COST')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Cash', 'Cash')], db_column='PaymentMethod', max_length=30)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], db_column='PaymentStatus', max_length=20)),
                ('payment_date', models.DateTimeField(db_column='PaymentDate')),
                ('booking', models.ForeignKey(db_column='BookingID', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='charging.booking')),
            ],
            options={
                'db_table': 'PAYMENTS',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='CK_PAYMENTS_AMOUNT'), models.CheckConstraint(condition=models.Q(('payment_method__in', ['UPI', 'Card', 'Cash'])), name='CK_PAYMENTS_METHOD'), models.CheckConstraint(condition=models.Q(('payment_status__in', ['Pending', 'Completed', 'Failed', 'Refunded'])), name='CK_PAYMENTS_STATUS')],
            },
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.UniqueConstraint(fields=('station', 'charger_number'), name='UQ_CHARGERS_NUMBER'),
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.CheckConstraint(condition=models.Q(('charger_type__in', ['AC', 'DC'])), name='CK_CHARGERS_TYPE'),
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.CheckConstraint(condition=models.Q(('power_output__gt', 0)), name='CK_CHARGERS_POWER'),
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_kwh__gt', 0)), name='CK_CHARGERS_PRICE'),
        ),
        migrations.AddConstraint(
            model_name='charger',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Available', 'Occupied', 'Maintenance'])), name='CK_CHARGERS_STATUS'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='CK_REVIEWS_RATING'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('is_read__in', ['Y', 'N'])), name='CK_NOTIFICATIONS_ISREAD'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceverification',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ['Approved', 'Rejected', 'Pending'])), name='CK_MAINT_VERIFICATION_RESULT'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='CK_BOOKINGS_TIME'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Pending', 'Confirmed', 'Completed', 'Cancelled'])), name='CK_BOOKINGS_STATUS'),
        ),
    ]
