CREATE TABLE PAYMENTS (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BookingID NUMBER NOT NULL,
    Amount NUMBER(10,2) NOT NULL,
    PaymentMethod VARCHAR2(30) NOT NULL,
    PaymentStatus VARCHAR2(20) NOT NULL,
    PaymentDate DATE NOT NULL,

    CONSTRAINT PK_PAYMENTS
        PRIMARY KEY (PaymentID),

    CONSTRAINT FK_PAYMENTS_BOOKING
        FOREIGN KEY (BookingID)
        REFERENCES BOOKINGS(BookingID),

    CONSTRAINT CK_PAYMENTS_AMOUNT
        CHECK (Amount > 0),

    CONSTRAINT CK_PAYMENTS_METHOD
        CHECK (PaymentMethod IN ('UPI', 'Card', 'Cash')),

    CONSTRAINT CK_PAYMENTS_STATUS
        CHECK (PaymentStatus IN ('Pending', 'Completed', 'Failed', 'Refunded'))
);
