CREATE TABLE STATIONS (
    StationID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    OwnerID NUMBER NOT NULL,
    StationName VARCHAR2(100) NOT NULL,
    Location VARCHAR2(255) NOT NULL,
    City VARCHAR2(50) NOT NULL,
    ChargerType VARCHAR2(30) NOT NULL,
    TotalPorts NUMBER NOT NULL,
    AvailablePorts NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,

    CONSTRAINT PK_STATIONS
        PRIMARY KEY (StationID),

    CONSTRAINT FK_STATIONS_OWNER
        FOREIGN KEY (OwnerID)
        REFERENCES USERS(UserID),

    CONSTRAINT CK_STATIONS_CHARGER
        CHECK (ChargerType IN ('AC', 'DC')),

    CONSTRAINT CK_STATION_PORTS
        CHECK (
            TotalPorts > 0
            AND AvailablePorts >= 0
            AND AvailablePorts <= TotalPorts
        ),

    CONSTRAINT CK_STATIONS_STATUS
        CHECK (Status IN ('Active', 'Inactive', 'Maintenance'))
);
